apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8083"
    spec:
      containers:
      - name: product-service
        image: sonyms2023/product-service:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: shop-config
        - secretRef:
            name: shop-secrets
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
