apiVersion: v1
kind: ConfigMap
metadata:
  namespace: apps
  name: shop-config
  labels:
    app: shop-microservices
data:
  EUREKA_URL: "http://eureka:8761/eureka/" # Disabled in k8s profile anyway
  KAFKA_BOOTSTRAP_SERVERS: "kafka.db.svc.cluster.local:9092"
  ZIPKIN_URL: "http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans"
  LOKI_URL: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
  DB_URL: "jdbc:postgresql://postgres.db.svc.cluster.local:5432/shop_db"
  DB_USERNAME: "shop_user"
  REDIS_HOST: "redis.db.svc.cluster.local"
  APP_CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://localhost,http://localhost:3000"
