apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sonyms/shop-microservices.git
    targetRevision: HEAD
    path: gitops/db
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
