server:
  port: 8083
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true
  application:
    name: product-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shop_db}
    username: ${DB_USERNAME:shop_user}
    password: ${DB_PASSWORD:shop_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: product-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:19411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  tracing:
    enabled: true
    sampling:
      probability: 0.1

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [traceId=%X{traceId:-}, spanId=%X{spanId:-}] - %msg%n"


---
spring:
  config:
    activate:
      on-profile: k8s
eureka:
  client:
    enabled: false
