apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
      - name: user-service
        image: sonyms2023/user-service:v1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: shop-config
        - secretRef:
            name: shop-secrets
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
