server:
  port: 8084
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1024

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  threads:
    virtual:
      enabled: true
  application:
    name: cart-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
      circuitbreaker:
        enabled: true


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: cart-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:19411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  tracing:
    enabled: true
    sampling:
      probability: 0.1

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [traceId=%X{traceId:-}, spanId=%X{spanId:-}] - %msg%n"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      product-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s




---
spring:
  config:
    activate:
      on-profile: k8s
eureka:
  client:
    enabled: false
feign:
  client:
    product:
      url: http://product-service:8083
    cart:
      url: http://cart-service:8084
